'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

if __name__ == "__main__":
    prev, curr = 0, 1
    total = 0
    max = 4000000

    while True:
        prev, curr = curr, curr + prev
        print("prev: "+str(prev))
        print("curr: "+str(curr))

        if curr >= max:
            break
        elif curr%2 == 0:
            total += curr
    
        print(total)
